"""
Optional GitHub Issues helpers for Standup Coach Agent.

The first step is to generate issue payloads locally. Later steps can decide
whether to print those payloads as a dry run or send them to the GitHub API.
"""


def create_issue_body(blocker, action_item):
    """Create a beginner-friendly GitHub issue body."""
    return (
        "## Standup Blocker\n"
        f"{blocker['blocker']}\n\n"
        "## Suggested Action\n"
        f"{action_item}\n\n"
        "## Team Member\n"
        f"{blocker['name']} - {blocker['role']}\n\n"
        "_Generated by Standup Coach Agent._"
    )


def build_github_issue_payloads(blockers, action_items):
    """Convert blockers and action items into GitHub issue payloads."""
    issue_payloads = []

    for index, blocker in enumerate(blockers):
        if index < len(action_items):
            action_item = action_items[index]
        else:
            action_item = f"Follow up with {blocker['name']} about this blocker."

        payload = {
            "title": f"Standup blocker: {blocker['name']}",
            "body": create_issue_body(blocker, action_item),
            "labels": ["standup", "blocker"],
        }

        github_username = blocker.get("github_username")
        if github_username:
            payload["assignees"] = [github_username]

        issue_payloads.append(payload)

    return issue_payloads
